### ISSUE TITLE
hpack encode_side_update panic: "value out of range"

### ISSUE THREAD

**Issue by jeromegn** [hyperium/h2#395]
A curious thing happened, 2 panics from the same server, same process, within a second. Both related to the h2 crate:

**Aug 17, 2019 3:33:15 PM UTC**

```
OS Version: Linux 4.18.0-21-generic (None)
Report Version: 104


Application Specific Information:
value out of range

Thread 0
0   h2                              0xc27b4e            h2::hpack::encoder::encode_int (encoder.rs:381)
1   h2                              0xc25cb1            [inlined] h2::hpack::encoder::encode_size_update (encoder.rs:260)
2   h2                              0xc25cb1            [inlined] h2::hpack::encoder::Encoder::encode_size_updates (encoder.rs:161)
3   h2                              0xc25cb1            h2::hpack::encoder::Encoder::encode (encoder.rs:85)
4   h2                              0xc1e4e3            [inlined] h2::frame::headers::EncodingHeaderBlock::encode (headers.rs:551)
5   h2                              0xc1e4e3            h2::frame::headers::Headers::encode (headers.rs:267)
6   h2                              0x42ed62            h2::codec::framed_write::FramedWrite<T>::buffer (framed_write.rs:128)
7   h2                              0x56811f            [inlined] h2::codec::Codec<T>::buffer (mod.rs:149)
8   h2                              0x56811f            [inlined] h2::proto::streams::prioritize::Prioritize::poll_complete (prioritize.rs:516)
9   h2                              0x56811f            h2::proto::streams::send::Send::poll_complete (send.rs:242)
10  h2                              0x4d7e8e            h2::proto::streams::streams::Streams<T>::poll_complete (streams.rs:595)
11  h2                              0x4819f6            h2::proto::connection::Connection<T>::poll (connection.rs:211)
12  h2                              0x4a1dc0            [inlined] h2::server::Connection<T>::poll_close (server.rs:424)
13  h2                              0x4a1dc0            <h2::server::Connection<T> as futures::stream::Stream>::poll (server.rs:487)
14  hyper                           0x44f518            [inlined] hyper::proto::h2::server::Serving<T>::poll_server (server.rs:164)
15  hyper                           0x44f518            [inlined] <hyper::proto::h2::server::Server<T> as futures::future::Future>::poll (server.rs:106)
16  futures                         0x44f518            <futures::future::either::Either<T> as futures::future::Future>::poll (either.rs:36)
17  futures                         0x5c18e0            [inlined] futures::future::option::<T>::poll (option.rs:12)
18  hyper                           0x5c18e0            <hyper::server::conn::Connection<T> as futures::future::Future>::poll (conn.rs:636)
19  fly_proxy                       0x4add87            [inlined] <fly_proxy::session::http::HttpSession as futures::future::Future>::poll (mod.rs:65)
20  fly_proxy                       0x4add87            <fly_proxy::session::Session as futures::future::Future>::poll (mod.rs:96)
21  fly_proxy                       0x5cb655            [inlined] <fly_proxy::dispatch::Machine as fly_proxy::dispatch::PollMachine>::poll_driving_session (mod.rs:185)
22  core                            0x5cb655            [inlined] core::ops::function::FnOnce::call_once (function.rs:231)
23  rent_to_own                     0x5cb655            [inlined] rent_to_own::RentToOwn<T>::with (lib.rs:179)
24  fly_proxy                       0x5cb655            [inlined] <fly_proxy::dispatch::MachineFuture as futures::future::Future>::poll (mod.rs:89)
25  fly_proxy                       0x5cb655            <fly_proxy::dispatch::DispatchFuture as futures::future::Future>::poll (mod.rs:85)
26  fly_proxy                       0x428ff6            [inlined] <fly_proxy::frontend::tls::Machine as fly_proxy::frontend::tls::PollMachine>::poll_dispatch (tls.rs:159)
27  fly_proxy                       0x428ff6            [inlined] <fly_proxy::frontend::tls::MachineFuture as futures::future::Future>::poll::{{closure}}::{{closure}} (tls.rs:74)
28  rent_to_own                     0x428ff6            [inlined] rent_to_own::RentToOwn<T>::with (lib.rs:179)
29  fly_proxy                       0x428ff6            [inlined] <fly_proxy::frontend::tls::MachineFuture as futures::future::Future>::poll::{{closure}} (tls.rs:74)
30  rent_to_own                     0x428ff6            rent_to_own::RentToOwn<T>::with (lib.rs:179)
31  fly_proxy                       0x50e143            [inlined] <fly_proxy::frontend::tls::MachineFuture as futures::future::Future>::poll (tls.rs:74)
32  fly_proxy                       0x50e143            <fly_proxy::frontend::tls::TlsHandlerFuture as futures::future::Future>::poll (tls.rs:70)
33  fly_proxy                       0x598440            <fly_proxy::runtime::Temporary<T> as futures::future::Future>::poll (runtime.rs:218)
34  alloc                           0xbfcb92            [inlined] <alloc::boxed::Box<T> as futures::future::Future>::poll (mod.rs:113)
35  futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::poll_future_notify::{{closure}} (mod.rs:329)
36  futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::enter::{{closure}} (mod.rs:399)
37  futures                         0xbfcb92            futures::task_impl::std::set (mod.rs:83)
38  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::enter (mod.rs:399)
39  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_fn_notify (mod.rs:291)
40  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_future_notify (mod.rs:329)
41  tokio_threadpool                0xbfc722            [inlined] tokio_threadpool::task::Task::run::{{closure}} (mod.rs:145)
42  core                            0xbfc722            [inlined] core::ops::function::FnOnce::call_once (function.rs:231)
43  std                             0xbfc722            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
44  std                             0xbfc722            std::panicking::try::do_call (panicking.rs:293)
45  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
46  std                             0xbf9db9            [inlined] std::panicking::try (panicking.rs:272)
47  std                             0xbf9db9            [inlined] std::panic::catch_unwind (panic.rs:394)
48  tokio_threadpool                0xbf9db9            tokio_threadpool::task::Task::run (mod.rs:130)
49  tokio_threadpool                0xbf3805            [inlined] tokio_threadpool::worker::Worker::run_task2 (mod.rs:567)
50  tokio_threadpool                0xbf3805            tokio_threadpool::worker::Worker::run_task (mod.rs:459)
51  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_steal_task (mod.rs:416)
52  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_run_task (mod.rs:301)
53  tokio_threadpool                0xbf2ee9            tokio_threadpool::worker::Worker::run (mod.rs:241)
54  tokio                           0xbcf11e            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}} (builder.rs:390)
55  tokio_timer                     0xbcf11e            [inlined] tokio_timer::timer::handle::with_default::{{closure}} (handle.rs:101)
56  std                             0xbcf11e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
57  std                             0xbcf11e            std::thread::local::LocalKey<T>::with (local.rs:245)
58  tokio_timer                     0xbcefdf            [inlined] tokio_timer::timer::handle::with_default (handle.rs:84)
59  tokio                           0xbcefdf            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}} (builder.rs:382)
60  tokio_timer                     0xbcefdf            [inlined] tokio_timer::clock::clock::with_default::{{closure}} (clock.rs:137)
61  std                             0xbcefdf            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
62  std                             0xbcefdf            std::thread::local::LocalKey<T>::with (local.rs:245)
63  tokio_timer                     0xbcf30b            [inlined] tokio_timer::clock::clock::with_default (clock.rs:117)
64  tokio                           0xbcf30b            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}} (builder.rs:381)
65  tokio_reactor                   0xbcf30b            [inlined] tokio_reactor::with_default::{{closure}} (lib.rs:237)
66  std                             0xbcf30b            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
67  std                             0xbcf30b            std::thread::local::LocalKey<T>::with (local.rs:245)
68  tokio_reactor                   0xbd090e            [inlined] tokio_reactor::with_default (lib.rs:217)
69  tokio                           0xbd090e            tokio::runtime::threadpool::builder::Builder::build::{{closure}} (builder.rs:380)
70  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::callback::Callback::call (callback.rs:22)
71  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}} (mod.rs:127)
72  tokio_executor                  0xbfd593            [inlined] tokio_executor::global::with_default::{{closure}} (global.rs:209)
73  std                             0xbfd593            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
74  std                             0xbfd593            std::thread::local::LocalKey<T>::with (local.rs:245)
75  tokio_executor                  0xbfd36e            [inlined] tokio_executor::global::with_default (global.rs:178)
76  tokio_threadpool                0xbfd36e            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}} (mod.rs:125)
77  std                             0xbfd36e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
78  std                             0xbfd36e            std::thread::local::LocalKey<T>::with (local.rs:245)
79  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::worker::Worker::do_run (mod.rs:116)
80  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::pool::Pool::spawn_thread::{{closure}} (mod.rs:344)
81  std                             0xbf53e1            std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:136)
82  std                             0xbfc67c            [inlined] std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:470)
83  std                             0xbfc67c            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
84  std                             0xbfc67c            std::panicking::try::do_call (panicking.rs:293)
85  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
86  std                             0xbf5ed0            [inlined] std::panicking::try (panicking.rs:272)
87  std                             0xbf5ed0            [inlined] std::panic::catch_unwind (panic.rs:394)
88  std                             0xbf5ed0            [inlined] std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:469)
89  core                            0xbf5ed0            core::ops::function::FnOnce::call_once{{vtable.shim}} (function.rs:231)
90  alloc                           0xdb513f            <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
91  alloc                           0xdcdc40            [inlined] <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
92  std                             0xdcdc40            [inlined] std::sys_common::thread::start_thread (thread.rs:13)
93  std                             0xdcdc40            std::sys::unix::thread::Thread::new::thread_start (thread.rs:79)
```

**Aug 17, 2019 3:33:16 PM UTC**

```
OS Version: Linux 4.18.0-21-generic (None)
Report Version: 104


Application Specific Information:
called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"

Thread 0
0   core                            0x60bf14            core::result::unwrap_failed (macros.rs:18)
1   core                            0x4d4380            [inlined] core::result::Result<T>::unwrap (result.rs:800)
2   h2                              0x4d4380            h2::proto::streams::streams::StreamRef<T>::reserve_capacity (streams.rs:953)
3   h2                              0x5e5f7d            [inlined] h2::share::SendStream<T>::reserve_capacity (share.rs:287)
4   hyper                           0x5e5f7d            <hyper::proto::h2::PipeToSendStream<T> as futures::future::Future>::poll (mod.rs:122)
5   hyper                           0x453d61            [inlined] hyper::proto::h2::server::H2Stream<T>::poll2 (server.rs:290)
6   hyper                           0x453d61            <hyper::proto::h2::server::H2Stream<T> as futures::future::Future>::poll (server.rs:308)
7   alloc                           0xbfcb92            [inlined] <alloc::boxed::Box<T> as futures::future::Future>::poll (mod.rs:113)
8   futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::poll_future_notify::{{closure}} (mod.rs:329)
9   futures                         0xbfcb92            [inlined] futures::task_impl::Spawn<T>::enter::{{closure}} (mod.rs:399)
10  futures                         0xbfcb92            futures::task_impl::std::set (mod.rs:83)
11  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::enter (mod.rs:399)
12  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_fn_notify (mod.rs:291)
13  futures                         0xbfc722            [inlined] futures::task_impl::Spawn<T>::poll_future_notify (mod.rs:329)
14  tokio_threadpool                0xbfc722            [inlined] tokio_threadpool::task::Task::run::{{closure}} (mod.rs:145)
15  core                            0xbfc722            [inlined] core::ops::function::FnOnce::call_once (function.rs:231)
16  std                             0xbfc722            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
17  std                             0xbfc722            std::panicking::try::do_call (panicking.rs:293)
18  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
19  std                             0xbf9db9            [inlined] std::panicking::try (panicking.rs:272)
20  std                             0xbf9db9            [inlined] std::panic::catch_unwind (panic.rs:394)
21  tokio_threadpool                0xbf9db9            tokio_threadpool::task::Task::run (mod.rs:130)
22  tokio_threadpool                0xbf3805            [inlined] tokio_threadpool::worker::Worker::run_task2 (mod.rs:567)
23  tokio_threadpool                0xbf3805            tokio_threadpool::worker::Worker::run_task (mod.rs:459)
24  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_steal_task (mod.rs:416)
25  tokio_threadpool                0xbf2ee9            [inlined] tokio_threadpool::worker::Worker::try_run_task (mod.rs:301)
26  tokio_threadpool                0xbf2ee9            tokio_threadpool::worker::Worker::run (mod.rs:241)
27  tokio                           0xbcf11e            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}} (builder.rs:390)
28  tokio_timer                     0xbcf11e            [inlined] tokio_timer::timer::handle::with_default::{{closure}} (handle.rs:101)
29  std                             0xbcf11e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
30  std                             0xbcf11e            std::thread::local::LocalKey<T>::with (local.rs:245)
31  tokio_timer                     0xbcefdf            [inlined] tokio_timer::timer::handle::with_default (handle.rs:84)
32  tokio                           0xbcefdf            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}} (builder.rs:382)
33  tokio_timer                     0xbcefdf            [inlined] tokio_timer::clock::clock::with_default::{{closure}} (clock.rs:137)
34  std                             0xbcefdf            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
35  std                             0xbcefdf            std::thread::local::LocalKey<T>::with (local.rs:245)
36  tokio_timer                     0xbcf30b            [inlined] tokio_timer::clock::clock::with_default (clock.rs:117)
37  tokio                           0xbcf30b            [inlined] tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}} (builder.rs:381)
38  tokio_reactor                   0xbcf30b            [inlined] tokio_reactor::with_default::{{closure}} (lib.rs:237)
39  std                             0xbcf30b            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
40  std                             0xbcf30b            std::thread::local::LocalKey<T>::with (local.rs:245)
41  tokio_reactor                   0xbd090e            [inlined] tokio_reactor::with_default (lib.rs:217)
42  tokio                           0xbd090e            tokio::runtime::threadpool::builder::Builder::build::{{closure}} (builder.rs:380)
43  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::callback::Callback::call (callback.rs:22)
44  tokio_threadpool                0xbfd593            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}} (mod.rs:127)
45  tokio_executor                  0xbfd593            [inlined] tokio_executor::global::with_default::{{closure}} (global.rs:209)
46  std                             0xbfd593            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
47  std                             0xbfd593            std::thread::local::LocalKey<T>::with (local.rs:245)
48  tokio_executor                  0xbfd36e            [inlined] tokio_executor::global::with_default (global.rs:178)
49  tokio_threadpool                0xbfd36e            [inlined] tokio_threadpool::worker::Worker::do_run::{{closure}} (mod.rs:125)
50  std                             0xbfd36e            [inlined] std::thread::local::LocalKey<T>::try_with (local.rs:299)
51  std                             0xbfd36e            std::thread::local::LocalKey<T>::with (local.rs:245)
52  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::worker::Worker::do_run (mod.rs:116)
53  tokio_threadpool                0xbf53e1            [inlined] tokio_threadpool::pool::Pool::spawn_thread::{{closure}} (mod.rs:344)
54  std                             0xbf53e1            std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:136)
55  std                             0xbfc67c            [inlined] std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:470)
56  std                             0xbfc67c            [inlined] <std::panic::AssertUnwindSafe<T> as core::ops::function::FnOnce<T>>::call_once (panic.rs:315)
57  std                             0xbfc67c            std::panicking::try::do_call (panicking.rs:293)
58  <unknown>                       0xdce5ea            __rust_maybe_catch_panic (lib.rs:85)
59  std                             0xbf5ed0            [inlined] std::panicking::try (panicking.rs:272)
60  std                             0xbf5ed0            [inlined] std::panic::catch_unwind (panic.rs:394)
61  std                             0xbf5ed0            [inlined] std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:469)
62  core                            0xbf5ed0            core::ops::function::FnOnce::call_once{{vtable.shim}} (function.rs:231)
63  alloc                           0xdb513f            <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
64  alloc                           0xdcdc40            [inlined] <alloc::boxed::Box<T> as core::ops::function::FnOnce<T>>::call_once (boxed.rs:704)
65  std                             0xdcdc40            [inlined] std::sys_common::thread::start_thread (thread.rs:13)
66  std                             0xdcdc40            std::sys::unix::thread::Thread::new::thread_start (thread.rs:79)
```

Running rust 1.36.0.

This only happened once, and we're serving a lot of requests. Still could be interesting to fix it though (if possible). Not panicking would probably be good if it's unfixable.

**Comment by seanmonstar** [comment]
Thanks for the report! The poison error most likely is just a result of the first one, the `encode_size_update` panic.

**Comment by 5225225** [comment]
I came across this when running the fuzzer (`fuzz_e2e`).

Reproduction:

```toml
[dependencies]
futures = "0.3.14"
h2 = "0.3.2"
http = "0.2.4"
tokio = { version = "1.5.0", features = ["full"] }
```

```rust
use futures::future;
use futures::stream::FuturesUnordered;
use futures::Stream;
use http::{Method, Request};
use std::future::Future;
use std::io;
use std::pin::Pin;
use std::task::{Context, Poll};
use tokio::io::{AsyncRead, AsyncWrite, ReadBuf};

struct MockIo<'a> {
    input: &'a [u8],
}

impl<'a> MockIo<'a> {
    fn next_byte(&mut self) -> Option<u8> {
        if let Some(&c) = self.input.first() {
            self.input = &self.input[1..];
            Some(c)
        } else {
            None
        }
    }

    fn next_u32(&mut self) -> u32 {
        (self.next_byte().unwrap_or(0) as u32) << 8 | self.next_byte().unwrap_or(0) as u32
    }
}

impl<'a> AsyncRead for MockIo<'a> {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut ReadBuf,
    ) -> Poll<io::Result<()>> {
        let mut len = self.next_u32() as usize;
        if self.input.is_empty() {
            Poll::Ready(Ok(()))
        } else if len == 0 {
            cx.waker().clone().wake();
            Poll::Pending
        } else {
            if len > self.input.len() {
                len = self.input.len();
            }

            if len > buf.remaining() {
                len = buf.remaining();
            }
            buf.put_slice(&self.input[len..]);
            self.input = &self.input[len..];
            Poll::Ready(Ok(()))
        }
    }
}

impl<'a> AsyncWrite for MockIo<'a> {
    fn poll_write(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<io::Result<usize>> {
        let len = std::cmp::min(self.next_u32() as usize, buf.len());
        if len == 0 {
            if self.input.is_empty() {
                Poll::Ready(Err(io::ErrorKind::BrokenPipe.into()))
            } else {
                cx.waker().clone().wake();
                Poll::Pending
            }
        } else {
            Poll::Ready(Ok(len))
        }
    }

    fn poll_flush(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }
    fn poll_shutdown(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }
}

async fn run() -> Result<(), h2::Error> {
    let script = [
        0, 114, 0, 0, 0, 0, 0, 5, 0, 0, 0, 4, 0, 0, 0, 114, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0,
        1, 114, 5, 1, 0, 0, 8, 15, 255, 5, 8, 255, 255, 0, 15, 65, 251, 255, 0, 2, 33, 255, 0, 0,
        0, 0, 0, 0, 60, 0, 0, 0, 114, 5, 1, 0, 0, 8, 15, 255, 5, 8, 255, 255, 0, 15, 1, 0, 255, 0,
        2, 33, 255, 128, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 123, 4, 0, 0, 0, 0, 0, 164, 0, 3, 2,
    ];

    let io = MockIo { input: &script };
    let (mut h2, mut connection) = h2::client::handshake(io).await?;
    let mut futs = FuturesUnordered::new();
    let future = future::poll_fn(|cx| {
        if let Poll::Ready(()) = Pin::new(&mut connection).poll(cx)? {
            return Poll::Ready(Ok::<_, h2::Error>(()));
        }
        while futs.len() < 128 {
            if !h2.poll_ready(cx)?.is_ready() {
                break;
            }
            let request = Request::builder()
                .method(Method::POST)
                .uri("https://example.com/")
                .body(())
                .unwrap();
            let (resp, mut send) = h2.send_request(request, false)?;
            send.send_data(vec![0u8; 32769].into(), true).unwrap();
            drop(send);
            futs.push(resp);
        }
        loop {
            match Pin::new(&mut futs).poll_next(cx) {
                Poll::Pending | Poll::Ready(None) => break,
                Poll::Ready(Some(Ok(_))) | Poll::Ready(Some(Err(_))) => {}
            }
        }
        Poll::Pending
    });
    future.await?;
    Ok(())
}

fn main() {
    let rt = tokio::runtime::Runtime::new().unwrap();
    let _res = rt.block_on(run());
}
```

```
thread 'main' panicked at 'value out of range', /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/hpack/encoder.rs:388:9
stack backtrace:
   0: std::panicking::begin_panic
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: h2::hpack::encoder::encode_int
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/hpack/encoder.rs:388:9
   2: h2::hpack::encoder::encode_size_update
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/hpack/encoder.rs:267:5
   3: h2::hpack::encoder::Encoder::encode_size_updates
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/hpack/encoder.rs:168:17
   4: h2::hpack::encoder::Encoder::encode
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/hpack/encoder.rs:95:25
   5: h2::frame::headers::EncodingHeaderBlock::encode
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/frame/headers.rs:640:34
   6: h2::frame::headers::Headers::encode
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/frame/headers.rs:281:9
   7: h2::codec::framed_write::Encoder<B>::buffer
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/codec/framed_write.rs:284:45
   8: h2::codec::framed_write::FramedWrite<T,B>::buffer
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/codec/framed_write.rs:115:9
   9: h2::codec::Codec<T,B>::buffer
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/codec/mod.rs:140:9
  10: h2::proto::streams::prioritize::Prioritize::poll_complete
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/proto/streams/prioritize.rs:503:21
  11: h2::proto::streams::send::Send::poll_complete
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/proto/streams/send.rs:301:9
  12: h2::proto::streams::streams::Inner::poll_complete
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/proto/streams/streams.rs:859:16
  13: h2::proto::streams::streams::Streams<B,P>::poll_complete
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/proto/streams/streams.rs:180:9
  14: h2::proto::connection::Connection<T,P,B>::poll
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/proto/connection.rs:255:36
  15: <h2::client::Connection<T,B> as core::future::future::Future>::poll
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.2/src/client.rs:1279:9
  16: scratch::run::{{closure}}::{{closure}}
             at ./main.rs:97:34
  17: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.14/src/future/poll_fn.rs:55:9
  18: scratch::run::{{closure}}
             at ./main.rs:122:5
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  20: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263:54
  21: tokio::coop::with_budget::{{closure}}
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:106:9
  22: std::thread::local::LocalKey<T>::try_with
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
  23: std::thread::local::LocalKey<T>::with
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
  24: tokio::coop::with_budget
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:99:5
  25: tokio::coop::budget
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:76:5
  26: tokio::park::thread::CachedParkThread::block_on
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263:31
  27: tokio::runtime::enter::Enter::block_on
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/enter.rs:151:13
  28: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/mod.rs:71:9
  29: tokio::runtime::Runtime::block_on
             at /home/jess/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/mod.rs:452:43
  30: scratch::main
             at ./main.rs:128:16
  31: core::ops::function::FnOnce::call_once
             at /home/jess/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
