### ISSUE TITLE
Panic at 'attempt to subtract with overflow', src/proto/streams/streams.rs:1292:5

### ISSUE THREAD

**Issue by le-invoker** [hyperium/h2#424]
Hi, I'm testing the `server_push` feature that was just recently merged, but tokio seems to always panic when using this feature.
Here is the code I use for the `server` and the `client`.

In `server_push2.rs`
```rust
use h2::server;

use bytes::*;
use http::uri;
use http::{Request, Response, StatusCode};

use std::error::Error;
use tokio::net::{TcpListener, TcpStream};

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn Error>> {
    let _ = env_logger::try_init();

    let mut listener = TcpListener::bind("127.0.0.1:5928").await?;

    println!("listening on {:?}", listener.local_addr());

    loop {
        if let Ok((socket, _peer_addr)) = listener.accept().await {
            tokio::spawn(async move {
                if let Err(e) = handle(socket).await {
                    println!("  -> err={:?}", e);
                }
            });
        }
    }
}

async fn handle(socket: TcpStream) -> Result<(), Box<dyn Error>> {
    let mut connection = server::handshake(socket).await?;
    println!("H2 connection bound");

    while let Some(result) = connection.accept().await {
        let (request, mut respond) = result?;
        println!("request uri: {}", request.uri());
        println!("GOT request: {:?}", request);
        let response = Response::builder().status(StatusCode::OK).body(()).unwrap();

        let mut pushed_uri_parts: uri::Parts  = request.into_parts().0.uri.into();
        pushed_uri_parts.path_and_query = uri::PathAndQuery::from_static("/pushed").into();
        let uri1 = uri::Uri::from_parts(pushed_uri_parts).unwrap();
        println!("uri1 {}", uri1);

        //let uri2 = uri::Uri::from_static("http://127.0.0.1:5928/pushed2");
        let uri2 = uri::Uri::from_static("https://http2.akamai.com/pushed2");

        println!("uri2 {}", uri2);

        let pushed_req = Request::builder()
            .uri(uri1)
            .body(())
            .unwrap();

        let pushed_req2 = Request::builder()
            .uri(uri2)
            .body(())
            .unwrap();

        let pushed_rsp = http::Response::builder().status(200).body(()).unwrap();
        let pushed_rsp2 = http::Response::builder().status(200).body(()).unwrap();
        let mut send_pushed = respond
            .push_request(pushed_req)
            .unwrap()
            .send_response(pushed_rsp, false)
            .unwrap();

        let mut send_pushed2 = respond
            .push_request(pushed_req2)
            .unwrap()
            .send_response(pushed_rsp2, false)
            .unwrap();

        let mut send = respond.send_response(response, false)?;

        println!(">>>> pushing data");
        send_pushed.send_data(Bytes::from_static(b"Pushed data!\n"), true)?;
        send_pushed2.send_data(Bytes::from_static(b"Another Pushed data!\n"), true)?;
        println!(">>>> sending data");
        send.send_data(Bytes::from_static(b"hello world"), true)?;
    }

    println!("~~~~~~~~~~~~~~~~~~~~~~~~~~~ H2 connection CLOSE !!!!!! ~~~~~~~~~~~");

    Ok(())
}
```

In `client.rs`

```rust
use h2::client;
use http::{HeaderMap, Request};

use std::error::Error;

use tokio::net::TcpStream;

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn Error>> {
    let _ = env_logger::try_init();

    let tcp = TcpStream::connect("127.0.0.1:5928").await?;
    let (mut client, h2) = client::handshake(tcp).await?;

    println!("sending request");

    let request = Request::builder()
        .uri("https://http2.akamai.com/")
        .body(())
        .unwrap();

    let request1 = Request::builder()
        .uri("https://http2.akamai.com/pushed")
        .body(())
        .unwrap();

    let request2 = Request::builder()
        .uri("https://http2.akamai.com/pushed2")
        .body(())
        .unwrap();

    let mut trailers = HeaderMap::new();
    trailers.insert("zomg", "hello".parse().unwrap());

    let (response, mut stream) = client.send_request(request, false).unwrap();
    let (response1, mut stream1) = client.send_request(request1, false).unwrap();
    let (response2, mut stream2) = client.send_request(request2, false).unwrap();

    // send trailers
    stream.send_trailers(trailers).unwrap();

    // Spawn a task to run the conn...
    tokio::spawn(async move {
        if let Err(e) = h2.await {
            println!("GOT ERR={:?}", e);
        }
    });

    let response = response.await?;
    println!("GOT RESPONSE: {:?}", response);

    let response1 = response1.await?;
    println!("GOT RESPONSE1: {:?}", response1);

    let response2 = response2.await?;
    println!("GOT RESPONSE2: {:?}", response1);

    // Get the body
    let mut body = response.into_body();
    let mut body1 = response1.into_body();
    let mut body2 = response2.into_body();

    while let Some(chunk) = body.data().await {
        println!("GOT CHUNK = {:?}", chunk?);
    }

    while let Some(chunk1) = body1.data().await {
        println!("GOT CHUNK1 = {:?}", chunk1?);
    }

    while let Some(chunk2) = body2.data().await {
        println!("GOT CHUNK2 = {:?}", chunk2?);
    }

    if let Some(trailers) = body.trailers().await? {
        println!("GOT TRAILERS: {:?}", trailers);
    }

    Ok(())
}
```

**Comment by seanmonstar** [comment]
It's not tokio panicking, it's likely `h2` panicking inside one of tokio's runtime threads. A message of "attempt to subtract with overflow" sounds like it could be related to h2's flow control.

Would you be able to run with `RUST_BACKTRACE=1` and paste the output?

**Comment by ivanceras** [comment]
Here is the backtrace:
```sh
RUST_BACKTRACE=1 cargo run --example server_push2
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/server_push2`
listening on Ok(V4(127.0.0.1:5928))
H2 connection bound
request uri: https://http2.akamai.com/
GOT request: Request { method: GET, uri: https://http2.akamai.com/, version: HTTP/2.0, headers: {}, body: RecvStream { inner: FlowControl { inner: OpaqueStreamRef { stream_id: StreamId(1), ref_count: 2 } } } }
uri1 https://http2.akamai.com/pushed
uri2 https://http2.akamai.com/pushed2
>>>> pushing data
>>>> sending data
request uri: https://http2.akamai.com/pushed
GOT request: Request { method: GET, uri: https://http2.akamai.com/pushed, version: HTTP/2.0, headers: {}, body: RecvStream { inner: FlowControl { inner: OpaqueStreamRef { stream_id: StreamId(3), ref_count: 2 } } } }
uri1 https://http2.akamai.com/pushed
uri2 https://http2.akamai.com/pushed2
>>>> pushing data
>>>> sending data
thread 'tokio-runtime-worker-0' panicked at 'attempt to subtract with overflow', src/proto/streams/streams.rs:1292:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:469
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:376
  12: rust_begin_unwind
             at src/libstd/panicking.rs:303
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: h2::proto::streams::streams::drop_stream_ref
             at src/proto/streams/streams.rs:1292
  16: <h2::proto::streams::streams::OpaqueStreamRef as core::ops::drop::Drop>::drop
             at src/proto/streams/streams.rs:1273
  17: core::ptr::real_drop_in_place
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ptr/mod.rs:175
  18: core::ptr::real_drop_in_place
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ptr/mod.rs:175
  19: core::ptr::real_drop_in_place
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ptr/mod.rs:175
  20: server_push2::handle::{{closure}}
             at examples/server_push2.rs:80
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  22: std::future::set_task_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:79
  23: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  24: std::future::poll_with_tls_context::{{closure}}
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:121
  25: std::future::get_task_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:111
  26: std::future::poll_with_tls_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:121
  27: server_push2::main::{{closure}}::{{closure}}
             at examples/server_push2.rs:21
  28: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  29: std::future::set_task_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:79
  30: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  31: tokio_executor::threadpool::task::Task::run::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/task/mod.rs:151
  32: core::ops::function::FnOnce::call_once
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ops/function.rs:227
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panic.rs:315
  34: std::panicking::try::do_call
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panicking.rs:288
  35: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  36: std::panicking::try
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panicking.rs:267
  37: std::panic::catch_unwind
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panic.rs:394
  38: tokio_executor::threadpool::task::Task::run
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/task/mod.rs:130
  39: tokio_executor::threadpool::worker::Worker::run_task2
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:560
  40: tokio_executor::threadpool::worker::Worker::run_task
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:452
  41: tokio_executor::threadpool::worker::Worker::try_run_owned_task
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:383
  42: tokio_executor::threadpool::worker::Worker::try_run_task
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:290
  43: tokio_executor::threadpool::worker::Worker::run
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:234
  44: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.6/src/runtime/threadpool/builder.rs:350
  45: tracing_core::dispatcher::with_default
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.6/src/dispatcher.rs:225
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.6/src/runtime/threadpool/builder.rs:349
  47: tokio_timer::clock::with_default::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.6/src/clock/mod.rs:155
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:262
  49: std::thread::local::LocalKey<T>::with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:239
  50: tokio_timer::clock::with_default
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.6/src/clock/mod.rs:135
  51: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.6/src/runtime/threadpool/builder.rs:347
  52: tokio_executor::threadpool::callback::Callback::call
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/callback.rs:20
  53: tokio_executor::threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:125
  54: tokio_executor::global::with_default::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/global.rs:173
  55: std::thread::local::LocalKey<T>::try_with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:262
  56: std::thread::local::LocalKey<T>::with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:239
  57: tokio_executor::global::with_default
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/global.rs:147
  58: tokio_executor::threadpool::worker::Worker::do_run::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:123
  59: std::thread::local::LocalKey<T>::try_with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:262
  60: std::thread::local::LocalKey<T>::with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:239
  61: tokio_executor::threadpool::worker::Worker::do_run
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:114
  62: tokio_executor::threadpool::pool::Pool::spawn_thread::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/pool/mod.rs:347
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by le-invoker** [comment]
Here is the backtrace
```sh
RUST_BACKTRACE=1 cargo run --example server_push2
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/server_push2`
listening on Ok(V4(127.0.0.1:5928))
H2 connection bound
request uri: https://http2.akamai.com/
GOT request: Request { method: GET, uri: https://http2.akamai.com/, version: HTTP/2.0, headers: {}, body: RecvStream { inner: FlowControl { inner: OpaqueStreamRef { stream_id: StreamId(1), ref_count: 2 } } } }
uri1 https://http2.akamai.com/pushed
uri2 https://http2.akamai.com/pushed2
>>>> pushing data
>>>> sending data
request uri: https://http2.akamai.com/pushed
GOT request: Request { method: GET, uri: https://http2.akamai.com/pushed, version: HTTP/2.0, headers: {}, body: RecvStream { inner: FlowControl { inner: OpaqueStreamRef { stream_id: StreamId(3), ref_count: 2 } } } }
uri1 https://http2.akamai.com/pushed
uri2 https://http2.akamai.com/pushed2
>>>> pushing data
>>>> sending data
thread 'tokio-runtime-worker-0' panicked at 'attempt to subtract with overflow', src/proto/streams/streams.rs:1292:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:469
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:376
  12: rust_begin_unwind
             at src/libstd/panicking.rs:303
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: h2::proto::streams::streams::drop_stream_ref
             at src/proto/streams/streams.rs:1292
  16: <h2::proto::streams::streams::OpaqueStreamRef as core::ops::drop::Drop>::drop
             at src/proto/streams/streams.rs:1273
  17: core::ptr::real_drop_in_place
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ptr/mod.rs:175
  18: core::ptr::real_drop_in_place
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ptr/mod.rs:175
  19: core::ptr::real_drop_in_place
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ptr/mod.rs:175
  20: server_push2::handle::{{closure}}
             at examples/server_push2.rs:80
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  22: std::future::set_task_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:79
  23: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  24: std::future::poll_with_tls_context::{{closure}}
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:121
  25: std::future::get_task_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:111
  26: std::future::poll_with_tls_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:121
  27: server_push2::main::{{closure}}::{{closure}}
             at examples/server_push2.rs:21
  28: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  29: std::future::set_task_context
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:79
  30: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/future.rs:43
  31: tokio_executor::threadpool::task::Task::run::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/task/mod.rs:151
  32: core::ops::function::FnOnce::call_once
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libcore/ops/function.rs:227
  33: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panic.rs:315
  34: std::panicking::try::do_call
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panicking.rs:288
  35: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  36: std::panicking::try
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panicking.rs:267
  37: std::panic::catch_unwind
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/panic.rs:394
  38: tokio_executor::threadpool::task::Task::run
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/task/mod.rs:130
  39: tokio_executor::threadpool::worker::Worker::run_task2
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:560
  40: tokio_executor::threadpool::worker::Worker::run_task
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:452
  41: tokio_executor::threadpool::worker::Worker::try_run_owned_task
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:383
  42: tokio_executor::threadpool::worker::Worker::try_run_task
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:290
  43: tokio_executor::threadpool::worker::Worker::run
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:234
  44: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.6/src/runtime/threadpool/builder.rs:350
  45: tracing_core::dispatcher::with_default
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.6/src/dispatcher.rs:225
  46: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.6/src/runtime/threadpool/builder.rs:349
  47: tokio_timer::clock::with_default::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.6/src/clock/mod.rs:155
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:262
  49: std::thread::local::LocalKey<T>::with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:239
  50: tokio_timer::clock::with_default
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.3.0-alpha.6/src/clock/mod.rs:135
  51: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.0-alpha.6/src/runtime/threadpool/builder.rs:347
  52: tokio_executor::threadpool::callback::Callback::call
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/callback.rs:20
  53: tokio_executor::threadpool::worker::Worker::do_run::{{closure}}::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:125
  54: tokio_executor::global::with_default::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/global.rs:173
  55: std::thread::local::LocalKey<T>::try_with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:262
  56: std::thread::local::LocalKey<T>::with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:239
  57: tokio_executor::global::with_default
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/global.rs:147
  58: tokio_executor::threadpool::worker::Worker::do_run::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:123
  59: std::thread::local::LocalKey<T>::try_with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:262
  60: std::thread::local::LocalKey<T>::with
             at /rustc/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/libstd/thread/local.rs:239
  61: tokio_executor::threadpool::worker::Worker::do_run
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/worker/mod.rs:114
  62: tokio_executor::threadpool::pool::Pool::spawn_thread::{{closure}}
             at /home/le/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.2.0-alpha.6/src/threadpool/pool/mod.rs:347
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by seanmonstar** [comment]
Thanks! Looks like sending a push promise doesn't increment the `refs` field, and so when it is dropped and decrements `refs`, it overflows. The fix likely just needs a `me.refs += 1;` line added in `fn send_push_promise`.
